{
 "title": "PV_MOUX",
 "description": "Moux Solar System",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "PV - Navigation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consommmation / Production / Injection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "CONSO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Instant",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "idx", "operator": "=", "value": "293" }
     ]
    }
   ]
  },
  {
   "title": "Synthèse  sur cette période",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Consommation",
     "measurement": "Instant",
     "query": "SELECT sum(\"value\")  / 60 FROM \"Instant\" WHERE (\"idx\" = '293') AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "idx", "operator": "=", "value": "293" }
     ]
    },
    {
     "alias": "Cumulus",
     "measurement": "Instant",
     "query": "SELECT sum(\"value\")  / 60 FROM \"Instant\" WHERE (\"idx\" = '293') AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "idx", "operator": "=", "value": "209" }
     ]
    }
   ]
  },
  { "title": "PV - Synthèse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Aujourd'hui",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Consommation",
     "measurement": "Instant",
     "query": "SELECT sum(\"value\")  / 60 FROM \"Instant\" WHERE (\"idx\" = '293') AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "idx", "operator": "=", "value": "293" }
     ]
    },
    {
     "alias": "Cumulus",
     "measurement": "Instant",
     "query": "SELECT sum(\"value\")  / 60 FROM \"Instant\" WHERE (\"idx\" = '293') AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "idx", "operator": "=", "value": "209" }
     ]
    }
   ]
  },
  {
   "title": "Ce mois",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Consommation",
     "measurement": "Instant",
     "query": "SELECT sum(\"value\")  / 60 FROM \"Instant\" WHERE (\"idx\" = '293') AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "idx", "operator": "=", "value": "293" }
     ]
    },
    {
     "alias": "Cumulus",
     "measurement": "Instant",
     "query": "SELECT sum(\"value\")  / 60 FROM \"Instant\" WHERE (\"idx\" = '293') AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "idx", "operator": "=", "value": "209" }
     ]
    }
   ]
  },
  { "title": ".", "type": "text", "gridPos": { "h": 8, "w": 1, "x": 10, "y": 10 } },
  {
   "title": "Cette année",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Consommation",
     "measurement": "Instant",
     "query": "SELECT sum(\"value\")  / 60 FROM \"Instant\" WHERE (\"idx\" = '293') AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "idx", "operator": "=", "value": "293" }
     ]
    },
    {
     "alias": "Cumulus",
     "measurement": "Instant",
     "query": "SELECT sum(\"value\")  / 60 FROM \"Instant\" WHERE (\"idx\" = '293') AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "idx", "operator": "=", "value": "209" }
     ]
    }
   ]
  },
  { "title": "Consommation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Consommation / Aujourd'hui / 30 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "kwatt", "label": "Energie - kW / 30m" }
   ],
   "targets": [
    {
     "alias": "EDF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Instant",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1800000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "idx", "operator": "=", "value": "293" }
     ]
    },
    {
     "alias": "Direct self-use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "selfuse_energy_hourly" }
     ]
    }
   ]
  },
  {
   "title": "Consommation / Ce mois",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth", "label": "Energy (kWh/interval)" }
   ],
   "targets": [
    {
     "alias": "EDF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Instant",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "idx", "operator": "=", "value": "293" }
     ]
    },
    {
     "alias": "Direct self-use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "selfuse_energy_daily" }
     ]
    }
   ]
  },
  {
   "title": "Consommation / Cette année",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth", "label": "Energy (kWh/interval)" }
   ],
   "targets": [
    {
     "alias": "EDF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Instant",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "idx", "operator": "=", "value": "293" }
     ]
    },
    {
     "alias": "Direct self-use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "selfuse_energy_daily" }
     ]
    }
   ]
  },
  { "title": "Consommation précédente", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Consommation / Hier / 30 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "kwatt", "label": "Energie - kW / 30m" }
   ],
   "targets": [
    {
     "alias": "EDF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Instant",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1800000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "idx", "operator": "=", "value": "293" }
     ]
    },
    {
     "alias": "Direct self-use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "selfuse_energy_hourly" }
     ]
    }
   ]
  },
  {
   "title": "Consommation / Mois dernier",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth", "label": "Energy (kWh/interval)" }
   ],
   "targets": [
    {
     "alias": "EDF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Instant",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "idx", "operator": "=", "value": "293" }
     ]
    },
    {
     "alias": "Direct self-use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "selfuse_energy_daily" }
     ]
    }
   ]
  },
  {
   "title": "Consommation / Année dernière",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth", "label": "Energy (kWh/interval)" }
   ],
   "targets": [
    {
     "alias": "EDF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Instant",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "idx", "operator": "=", "value": "293" }
     ]
    },
    {
     "alias": "Direct self-use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "selfuse_energy_daily" }
     ]
    }
   ]
  },
  {
   "title": "Solaire",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Production",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "yaxes": [
      { "format": "kwatth" }
     ],
     "targets": [
      {
       "alias": "Exported Energy",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kWh",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "exported_energy_hourly" }
       ]
      },
      {
       "alias": "Direct self-use",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kWh",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "selfuse_energy_hourly" }
       ]
      }
     ]
    },
    {
     "title": "Yield",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "yaxes": [
      { "format": "kwatth" }
     ],
     "targets": [
      {
       "alias": "Exported Energy",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kWh",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "exported_energy_daily" }
       ]
      },
      {
       "alias": "Direct self-use",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kWh",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "selfuse_energy_daily" }
       ]
      }
     ]
    },
    {
     "title": "Balance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "yaxes": [
      { "format": "kwatth", "label": "Energy (kWh/interval)" }
     ],
     "targets": [
      {
       "alias": "Grid Consumption",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kWh",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "grid_consumption_energy_hourly" }
       ]
      },
      {
       "alias": "Exported Energy",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kWh",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "exported_energy_hourly" }
       ]
      }
     ]
    },
    {
     "title": "Energy blance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "yaxes": [
      { "format": "kwatth", "label": "Energy (kWh/interval)" }
     ],
     "targets": [
      {
       "alias": "Grid Consumption",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kWh",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "grid_consumption_energy_daily" }
       ]
      },
      {
       "alias": "Exported Energy",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kWh",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "exported_energy_daily" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cumulus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consommation / Aujourd'hui / 30 min",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "kwatt", "label": "Energie - kW / 30m" }
     ],
     "targets": [
      {
       "alias": "EDF",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Instant",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "integral"
         },
         { "params": [ " / 1800000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "idx", "operator": "=", "value": "209" }
       ]
      },
      {
       "alias": "Direct self-use",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kWh",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "selfuse_energy_hourly" }
       ]
      }
     ]
    },
    {
     "title": "Consommation / Ce mois",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "yaxes": [
      { "format": "kwatth", "label": "Energy (kWh/interval)" }
     ],
     "targets": [
      {
       "alias": "EDF",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Instant",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "integral"
         },
         { "params": [ " / 3600000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "idx", "operator": "=", "value": "209" }
       ]
      },
      {
       "alias": "Direct self-use",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kWh",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "selfuse_energy_daily" }
       ]
      }
     ]
    },
    {
     "title": "Consommation / Mois dernier",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "yaxes": [
      { "format": "kwatth", "label": "Energy (kWh/interval)" }
     ],
     "targets": [
      {
       "alias": "EDF",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Instant",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "integral"
         },
         { "params": [ " / 3600000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "idx", "operator": "=", "value": "209" }
       ]
      },
      {
       "alias": "Direct self-use",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kWh",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "selfuse_energy_daily" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Documentation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Solar System",
   "type": "text",
   "gridPos": { "h": 34, "w": 8, "x": 0, "y": 37 },
   "options": {
    "content": "<div  id='write'  class = 'is-node'><p>\r\n<span>By installing three phase Wifi_Mqtt_SmartMeter energy meter in your solar system, and clamping the first PZEM  onto grid, the second PZEM  onto solar inverter and the third PZEM onto load if applicable, you can monitor &quot;Grid Consumption Energy&quot; (the energy consumed from the grid), &quot;Exported Energy&quot; (the energy exported to the grid) and the energy produced by solar inverter. You can monitor the energy flow of the solar system.</span></p><p><span>Enjoy and have fun on </span>\r\n<a href='https://github.com/Coturex/Wifi_Mqtt_SolarBalancer' target='_blank'><span>Solar Balancer</span></a></p>\r\n<p><img src=\"https://user-images.githubusercontent.com/53934994/149093531-c04b23e2-a036-4c32-84a2-b24550343f8d.png\" referrerpolicy=\"no-referrer\" alt=\"img\"></p></div>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memo-tips",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 37 },
   "options": {
    "content": "# Title\nhttps://community.grafana.com/t/daily-power-consumption-from-watts/16196/30          "
   }
  }
 ]
}